"use client";
import { useState } from "react";
import Link from "next/link";
import { Bookmark, ChevronDown, Copy, Eye, Flag, Heart, HeartHandshake, MapPin, MessageCircle, MoreHorizontal, PartyPopper, Send, Share2, ShieldAlert, Smile, UserX } from "lucide-react";
import type { CommunityPost, ReactionType } from "@/lib/community/types";
import TrustBadge from "./TrustBadge";

const typeLabels: Record<CommunityPost["type"],string>={LOST_ITEM:"Lost item",FOUND_ITEM:"Found item",MISSING_PET:"Missing pet",LOST_DOCUMENT:"Lost document",FOUND_DOCUMENT:"Found document",VEHICLE:"Vehicle",NEED_HELP:"Need help",RECOVERED_ITEM:"Recovered item",SUCCESS_STORY:"Success story",COMMUNITY_UPDATE:"Community update"};
const reactions: Array<[ReactionType,string,typeof Heart]>=[["LIKE","Like",Heart],["HELPFUL","Helpful",HeartHandshake],["HOPE","Hope",Smile],["FOUND_IT","Found it",MapPin],["CELEBRATE","Celebrate",PartyPopper]];

export default function CommunityPostCard({post}:{post:CommunityPost}){const [saved,setSaved]=useState(false);const [expanded,setExpanded]=useState(false);const [reaction,setReaction]=useState<ReactionType|null>(null);const [commentsOpen,setCommentsOpen]=useState(false);return <article className="community-card community-post-card">
  <header className="post-header"><span className="post-avatar">{post.author.initials}</span><div><strong>{post.author.displayName}{post.author.verified&&<TrustBadge type="VERIFIED_USER" compact/>}</strong><small>@{post.author.username} · {post.createdAt} · {post.visibility.toLowerCase()}</small></div><details className="post-more"><summary aria-label="Post safety and sharing menu"><MoreHorizontal size={20}/></summary><div><button type="button"><Copy size={15}/>Copy link</button><button type="button"><Flag size={15}/>Report</button><button type="button"><Eye size={15}/>Hide</button><button type="button"><UserX size={15}/>Block</button></div></details></header>
  <div className="post-body"><div className="post-badges"><span className={`status-chip ${post.status.toLowerCase()}`}>{post.status.replaceAll("_"," ")}</span><span>{typeLabels[post.type]}</span>{post.author.badges?.slice(0,1).map(b=><TrustBadge key={b} type={b}/>)}</div><h2>{post.title}</h2><p>{expanded||post.description.length<150?post.description:`${post.description.slice(0,150)}…`} {post.description.length>=150&&<button className="read-more" type="button" onClick={()=>setExpanded(v=>!v)}>{expanded?"Show less":"Read more"}</button>}</p><div className="post-facts">{post.location&&<span><MapPin size={14}/>{post.location}</span>}<span>{post.category}</span>{post.reward&&<span className="reward">{post.reward}</span>}</div><div className="post-tags">{post.tags.map(tag=><span key={tag}>#{tag}</span>)}</div></div>
  <div className="post-media-fallback" role="img" aria-label={`${post.category} post media placeholder`}><span>{post.category}</span><small>Privacy-safe media area</small></div>
  <div className="post-metrics"><span>{Object.values(post.reactions).reduce((a,b)=>a+(b||0),0)} reactions</span><span>{post.commentCount} comments · {post.viewCount} views</span></div>
  <div className="post-actions"><details className="reaction-picker"><summary className={reaction?"selected":""}><Heart size={18}/>{reaction?reactions.find(r=>r[0]===reaction)?.[1]:"React"}</summary><div>{reactions.map(([value,label,Icon])=><button type="button" key={value} onClick={()=>setReaction(value)} aria-pressed={reaction===value}><Icon size={17}/>{label}</button>)}</div></details><button type="button" onClick={()=>setCommentsOpen(v=>!v)}><MessageCircle size={18}/>Comment</button><button type="button" onClick={()=>navigator.share?.({title:post.title,url:location.href})}><Share2 size={18}/>Share</button><button type="button" className={saved?"selected":""} onClick={()=>setSaved(v=>!v)} aria-pressed={saved}><Bookmark size={18}/>{saved?"Saved":"Save"}</button></div>
  <div className="post-primary-actions"><Link href={post.status==="LOST"?"/report-found-item":"/lost-items"}>{post.status==="LOST"?"I found this item":"This may be mine"}</Link><button type="button"><Send size={16}/>Send helpful information</button></div>
  {commentsOpen&&<section className="comments-panel" aria-label="Comments"><div className="comment-sort"><strong>Comments</strong><button type="button">Most helpful <ChevronDown size={14}/></button></div><form onSubmit={e=>e.preventDefault()}><label className="visually-hidden" htmlFor={`comment-${post.id}`}>Add a comment</label><input id={`comment-${post.id}`} placeholder="Add a helpful comment…"/><button type="submit" aria-label="Post comment"><Send size={17}/></button></form><div className="comment-empty"><MessageCircle size={22}/><span>Comment UI preview</span><small>Persistence is disabled until the community backend is available.</small></div></section>}
  <footer className="post-safety"><ShieldAlert size={14}/>Never pay before verification. Meet in a public place and keep sensitive details private.</footer>
 </article>}
