"use client";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { itemCategories } from "@/lib/validations/item";
import { Send, ShieldCheck } from "lucide-react";

export default function FoundReportForm({ recoveryCode = "" }: { recoveryCode?: string }) {
  const router = useRouter(); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  const [form, setForm] = useState({ recoveryCode, category: "Other", brand: "", modelNumber: "", color: "", identifyingMarks: "", description: "", foundLocation: "", foundDate: new Date().toISOString().slice(0, 16), finderName: "", finderPhone: "", finderWhatsapp: "", finderEmail: "", message: "" });
  function field(name: keyof typeof form, value: string) { setForm((current) => ({ ...current, [name]: value })); }
  async function submit(event: FormEvent) { event.preventDefault(); setLoading(true); setError(""); try { const response = await fetch("/api/found-reports", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const body = await response.json(); if (!response.ok) { setError(body.message ?? "Unable to notify owner."); return; } if (body.data.chatToken) router.push(`/chat/finder/${body.data.chatToken}`); else router.push(`/report-found-item/success?id=${body.data.reportId}`); } catch { setError("Unable to submit report. Check your connection and try again."); } finally { setLoading(false); } }
  return <form className="enterprise-form" onSubmit={submit}>{error ? <div className="auth-alert error" role="alert">{error}</div> : null}<div className="form-section-head"><span><ShieldCheck size={20} /></span><div><h3>Found item details</h3><p>Share only what is needed to identify and return the item.</p></div></div><div className="row g-4">
    <div className="col-md-6"><label>Recovery ID <small>Optional</small><input value={form.recoveryCode} onChange={(e) => field("recoveryCode", e.target.value.toUpperCase())} placeholder="KP-82X4F" /></label></div>
    <div className="col-md-6"><label>Category<select value={form.category} onChange={(e) => field("category", e.target.value)}>{itemCategories.map((value) => <option key={value}>{value}</option>)}</select></label></div>
    <div className="col-md-4"><label>Brand <small>Optional</small><input value={form.brand} onChange={(e) => field("brand", e.target.value)} /></label></div><div className="col-md-4"><label>Model <small>Optional</small><input value={form.modelNumber} onChange={(e) => field("modelNumber", e.target.value)} /></label></div><div className="col-md-4"><label>Color <small>Optional</small><input value={form.color} onChange={(e) => field("color", e.target.value)} /></label></div>
    <div className="col-12"><label>Description<textarea rows={4} value={form.description} onChange={(e) => field("description", e.target.value)} minLength={10} required placeholder="Describe the item without posting sensitive personal data" /></label></div><div className="col-12"><label>Unique marks <small>Optional</small><input value={form.identifyingMarks} onChange={(e) => field("identifyingMarks", e.target.value)} /></label></div>
    <div className="col-md-6"><label>Found location<input value={form.foundLocation} onChange={(e) => field("foundLocation", e.target.value)} required /></label></div><div className="col-md-6"><label>Date & time found<input type="datetime-local" value={form.foundDate} onChange={(e) => field("foundDate", e.target.value)} required /></label></div>
    <div className="col-md-6"><label>Your name <small>Optional</small><input value={form.finderName} onChange={(e) => field("finderName", e.target.value)} /></label></div><div className="col-md-6"><label>Email <small>Optional</small><input type="email" value={form.finderEmail} onChange={(e) => field("finderEmail", e.target.value)} /></label></div><div className="col-md-6"><label>Phone <small>Optional</small><input value={form.finderPhone} onChange={(e) => field("finderPhone", e.target.value)} /></label></div><div className="col-md-6"><label>WhatsApp <small>Optional</small><input value={form.finderWhatsapp} onChange={(e) => field("finderWhatsapp", e.target.value)} /></label></div>
    <div className="col-12"><label>Message to owner<textarea rows={4} value={form.message} onChange={(e) => field("message", e.target.value)} required placeholder="Tell the owner how they can recover the item safely" /></label></div>
  </div><div className="privacy-inline"><ShieldCheck size={17} /> Owner contact details remain private. You do not need an account.</div><button className="btn btn-primary-kp" disabled={loading} type="submit"><Send size={17} /> {loading ? "Matching securely…" : "Notify Owner"}</button></form>;
}
