import { notFound } from "next/navigation";
import Link from "next/link";
import ModerationQueue from "@/components/admin/ModerationQueue";
import { getAdmin } from "@/lib/admin";
import { prisma } from "@/lib/prisma";

export default async function ModerationPage({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}) {
  if(!await getAdmin())notFound();const query=await searchParams;const page=Math.max(1,Number(query.page)||1);const take=25;
  const where={...(query.status?{decision:query.status as "APPROVED"|"UNDER_REVIEW"|"REJECTED"}:{}),...(query.type?{targetType:query.type as "POST"|"COMMENT"|"MEDIA"}:{}),...(query.provider?{provider:{contains:query.provider,mode:"insensitive" as const}}:{}),...(query.risk==="HIGH"?{riskScore:{gte:.7}}:query.risk==="MEDIUM"?{riskScore:{gte:.4,lt:.7}}:query.risk==="LOW"?{riskScore:{lt:.4}}:{})};
  const [cases,total]=await Promise.all([prisma.moderationCase.findMany({where,orderBy:{createdAt:"desc"},skip:(page-1)*take,take,include:{actions:{orderBy:{createdAt:"desc"},take:1}}}),prisma.moderationCase.count({where})]);
  const ownerIds=[...new Set(cases.flatMap(item=>item.ownerId?[item.ownerId]:[]))];const owners=await prisma.user.findMany({where:{id:{in:ownerIds}},select:{id:true,name:true}});const names=new Map(owners.map(owner=>[owner.id,owner.name]));
  return <main className="container py-5"><div className="d-flex justify-content-between"><div><span>Admin</span><h1>Content moderation</h1><p>Review provider decisions and apply audited actions.</p></div><Link href="/admin">Back to admin</Link></div><form className="row g-2 mb-4"><div className="col"><select name="status" defaultValue={query.status||""}><option value="">All statuses</option><option>UNDER_REVIEW</option><option>APPROVED</option><option>REJECTED</option></select></div><div className="col"><select name="type" defaultValue={query.type||""}><option value="">All targets</option><option>POST</option><option>COMMENT</option><option value="MEDIA">Images / videos</option></select></div><div className="col"><select name="risk" defaultValue={query.risk||""}><option value="">All risks</option><option>HIGH</option><option>MEDIUM</option><option>LOW</option></select></div><div className="col"><input name="provider" defaultValue={query.provider||""} placeholder="Provider"/></div><div className="col"><button>Filter</button></div></form><ModerationQueue cases={cases.map(item=>({id:item.id,createdAt:item.createdAt.toISOString(),targetType:item.targetType,targetId:item.targetId,decision:item.decision,riskScore:item.riskScore,reasonCode:item.reasonCode,provider:item.provider,ownerName:item.ownerId?names.get(item.ownerId)??null:null,signals:Array.isArray(item.signals)?item.signals.filter((value):value is string=>typeof value==="string"):[],lastAction:item.actions[0]?.action??null}))}/><nav className="d-flex gap-3 mt-4">{page>1&&<Link href={`?page=${page-1}`}>Previous</Link>}<span>Page {page} of {Math.max(1,Math.ceil(total/take))}</span>{page*take<total&&<Link href={`?page=${page+1}`}>Next</Link>}</nav></main>;
}
