"use client";
import { useEffect, useState } from "react";
import { HelpCircle, Send } from "lucide-react";
type Question = { id?: string; question: string; answer?: string | null; status?: string };
export default function VerificationPanel({ mode, conversationId, token }: { mode: "OWNER" | "FINDER"; conversationId?: string; token?: string }) {
  const [questions, setQuestions] = useState<Question[]>([]); const [selected, setSelected] = useState<string[]>([]); const [answers, setAnswers] = useState<Record<string, string>>({}); const [feedback, setFeedback] = useState(""); const [loading, setLoading] = useState(false);
  const base = mode === "OWNER" ? `/api/dashboard/chats/${conversationId}` : `/api/chat/finder/${token}`;
  async function load(suggestions = false) { const response = await fetch(base + (suggestions ? "/verification-suggestions" : "/verification-questions"), { cache: "no-store" }); const body = await response.json(); if (response.ok) setQuestions((body.data.questions as Array<string | Question>).map((entry) => typeof entry === "string" ? { question: entry } : entry)); }
  useEffect(() => { const timer = window.setTimeout(() => void load(mode === "OWNER"), 0); return () => window.clearTimeout(timer); }, []); // eslint-disable-line react-hooks/exhaustive-deps
  async function sendQuestions() { setLoading(true); const response = await fetch(`${base}/verification-questions`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ questions: selected }) }); const body = await response.json(); setFeedback(response.ok ? "Questions sent securely." : body.message); if (response.ok) setQuestions(body.data.questions); setLoading(false); }
  async function sendAnswers() { setLoading(true); const payload = questions.filter((q) => q.id && answers[q.id]).map((q) => ({ questionId: q.id, answer: answers[q.id!] })); const response = await fetch(`${base}/verification-answers`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ answers: payload }) }); const body = await response.json(); setFeedback(response.ok ? "Answers sent to the owner." : body.message); if (response.ok) void load(); setLoading(false); }
  async function review(id: string, status: "VERIFIED" | "REJECTED") { await fetch(`${base}/verification-questions/${id}/status`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status }) }); void load(); }
  if (!questions.length) return null;
  return <section className="verification-panel"><div className="verification-panel-head"><HelpCircle size={19} /><div><h3>Smart verification</h3><p>Never share passwords, PINs, OTPs or a full serial number.</p></div></div>{questions.map((q) => <article className="verification-question" key={q.id ?? q.question}>{mode === "OWNER" && !q.id ? <label><input type="checkbox" checked={selected.includes(q.question)} onChange={(e) => setSelected((current) => e.target.checked ? [...current, q.question] : current.filter((value) => value !== q.question))} /> {q.question}</label> : <><strong>{q.question}</strong>{q.answer ? <p>{q.answer}</p> : null}{mode === "FINDER" && q.id && q.status === "SENT" ? <textarea value={answers[q.id] ?? ""} onChange={(e) => setAnswers((current) => ({ ...current, [q.id!]: e.target.value }))} placeholder="Your answer" /> : null}{mode === "OWNER" && q.id && q.status === "ANSWERED" ? <div className="message-actions"><button type="button" className="btn btn-secondary-kp btn-sm-pill" onClick={() => void review(q.id!, "VERIFIED")}>Verify</button><button type="button" className="btn btn-secondary-kp btn-sm-pill" onClick={() => void review(q.id!, "REJECTED")}>Reject</button></div> : null}{q.status ? <span className="status-pill">{q.status}</span> : null}</>}</article>)}{mode === "OWNER" && questions.some((q) => !q.id) ? <button type="button" disabled={!selected.length || loading} className="btn btn-primary-kp" onClick={() => void sendQuestions()}><Send size={16} /> Send selected</button> : null}{mode === "FINDER" && questions.some((q) => q.status === "SENT") ? <button type="button" disabled={!Object.values(answers).some(Boolean) || loading} className="btn btn-primary-kp" onClick={() => void sendAnswers()}>Submit answers</button> : null}{feedback ? <p className="form-feedback">{feedback}</p> : null}</section>;
}
