CREATE TYPE "FoundReportStatus" AS ENUM ('NEW','MATCHED','CLOSED','SPAM');
CREATE TYPE "FoundMatchStatus" AS ENUM ('PENDING','OWNER_NOTIFIED','REJECTED','CONFIRMED');
CREATE TYPE "VerificationLevel" AS ENUM ('EMAIL','MOBILE','GOVERNMENT_ID','PREMIUM');
CREATE TYPE "VerificationRequestType" AS ENUM ('EMAIL','MOBILE','GOVERNMENT_ID','PREMIUM');
CREATE TYPE "VerificationRequestStatus" AS ENUM ('PENDING','APPROVED','REJECTED');
CREATE TYPE "ItemVerificationType" AS ENUM ('INVOICE','WARRANTY_CARD','OWNERSHIP_PROOF','SERIAL_NUMBER','PRODUCT_BOX','OTHER');
CREATE TYPE "ItemVerificationStatus" AS ENUM ('PENDING','APPROVED','REJECTED');
CREATE TYPE "ConversationVerificationStatus" AS ENUM ('PENDING','QUESTIONS_SENT','ANSWERED','VERIFIED','NOT_VERIFIED');
CREATE TYPE "ChatMessageStatus" AS ENUM ('SENT','DELIVERED','READ');
CREATE TYPE "VerificationQuestionStatus" AS ENUM ('DRAFT','SENT','ANSWERED','VERIFIED','REJECTED');
CREATE TYPE "RecoverySource" AS ENUM ('QR_SCAN','RECOVERY_ID','FOUND_REPORT','AI_MATCH','ADMIN');
CREATE TYPE "RecoveryStatus" AS ENUM ('REGISTERED','LOST','OWNER_NOTIFIED','CHAT_STARTED','VERIFYING_OWNERSHIP','MEETING_SCHEDULED','RETURNED','COMPLETED','STILL_MISSING','FALSE_REPORT','CANCELLED');
CREATE TYPE "RecoveryActorType" AS ENUM ('OWNER','FINDER','SYSTEM','ADMIN');
ALTER TYPE "ChatSenderType" ADD VALUE 'ADMIN';
ALTER TYPE "ConversationStatus" ADD VALUE 'RECOVERED';
ALTER TYPE "ItemStatus" ADD VALUE 'RECOVERED';
ALTER TYPE "NotificationType" ADD VALUE 'FOUND_REPORT';
ALTER TYPE "NotificationType" ADD VALUE 'POSSIBLE_MATCH';
ALTER TYPE "NotificationType" ADD VALUE 'VERIFICATION_UPDATE';
ALTER TYPE "NotificationType" ADD VALUE 'RECOVERY_UPDATE';

ALTER TABLE "ChatMessage" ADD COLUMN "finderIdentityId" TEXT, ADD COLUMN "imageUrl" TEXT, ADD COLUMN "locationJson" JSONB, ADD COLUMN "status" "ChatMessageStatus" NOT NULL DEFAULT 'SENT';
ALTER TABLE "Conversation" ADD COLUMN "finderIdentityId" TEXT, ADD COLUMN "foundReportId" TEXT, ADD COLUMN "verificationStatus" "ConversationVerificationStatus" NOT NULL DEFAULT 'PENDING';
ALTER TABLE "Item" ADD COLUMN "brand" TEXT, ADD COLUMN "color" TEXT, ADD COLUMN "emergencyContact" TEXT, ADD COLUMN "estimatedValue" DECIMAL(12,2), ADD COLUMN "identifyingMarks" TEXT, ADD COLUMN "lastSeenLocation" TEXT, ADD COLUMN "lostDate" TIMESTAMP(3), ADD COLUMN "modelNumber" TEXT, ADD COLUMN "publicSearchVisible" BOOLEAN NOT NULL DEFAULT false, ADD COLUMN "purchaseDate" TIMESTAMP(3), ADD COLUMN "qrRecoveryEnabled" BOOLEAN NOT NULL DEFAULT true, ADD COLUMN "recoveryCode" TEXT, ADD COLUMN "recoveryPreference" TEXT, ADD COLUMN "visibility" TEXT NOT NULL DEFAULT 'PRIVATE';
ALTER TABLE "User" ADD COLUMN "emailVerifiedAt" TIMESTAMP(3), ADD COLUMN "governmentIdVerifiedAt" TIMESTAMP(3), ADD COLUMN "lastActiveAt" TIMESTAMP(3), ADD COLUMN "mobileVerifiedAt" TIMESTAMP(3), ADD COLUMN "premiumVerifiedUntil" TIMESTAMP(3), ADD COLUMN "trustScore" INTEGER NOT NULL DEFAULT 0, ADD COLUMN "verificationLevel" "VerificationLevel";

CREATE TABLE "ItemImage" ("id" TEXT NOT NULL,"itemId" TEXT NOT NULL,"imageUrl" TEXT NOT NULL,"publicId" TEXT,"sortOrder" INTEGER NOT NULL DEFAULT 0,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "ItemImage_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Category" ("id" TEXT NOT NULL,"name" TEXT NOT NULL,"slug" TEXT NOT NULL,"icon" TEXT,"isActive" BOOLEAN NOT NULL DEFAULT true,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "Category_pkey" PRIMARY KEY ("id"));
CREATE TABLE "FinderIdentity" ("id" TEXT NOT NULL,"name" TEXT,"phone" TEXT,"whatsapp" TEXT,"email" TEXT,"phoneVerifiedAt" TIMESTAMP(3),"emailVerifiedAt" TIMESTAMP(3),"reputationScore" INTEGER NOT NULL DEFAULT 0,"successfulRecoveries" INTEGER NOT NULL DEFAULT 0,"helpfulReports" INTEGER NOT NULL DEFAULT 0,"falseReports" INTEGER NOT NULL DEFAULT 0,"avgResponseTime" INTEGER,"badges" JSONB,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "FinderIdentity_pkey" PRIMARY KEY ("id"));
CREATE TABLE "FoundReport" ("id" TEXT NOT NULL,"recoveryCode" TEXT,"category" TEXT NOT NULL,"brand" TEXT,"modelNumber" TEXT,"color" TEXT,"identifyingMarks" TEXT,"description" TEXT NOT NULL,"foundLocation" TEXT NOT NULL,"foundDate" TIMESTAMP(3) NOT NULL,"photoUrl" TEXT,"finderName" TEXT,"finderPhone" TEXT,"finderWhatsapp" TEXT,"finderEmail" TEXT,"message" TEXT NOT NULL,"status" "FoundReportStatus" NOT NULL DEFAULT 'NEW',"finderIdentityId" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "FoundReport_pkey" PRIMARY KEY ("id"));
CREATE TABLE "FoundReportImage" ("id" TEXT NOT NULL,"foundReportId" TEXT NOT NULL,"imageUrl" TEXT NOT NULL,"publicId" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "FoundReportImage_pkey" PRIMARY KEY ("id"));
CREATE TABLE "FoundReportMatch" ("id" TEXT NOT NULL,"foundReportId" TEXT NOT NULL,"itemId" TEXT NOT NULL,"matchScore" INTEGER NOT NULL,"matchReason" TEXT NOT NULL,"status" "FoundMatchStatus" NOT NULL DEFAULT 'PENDING',"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "FoundReportMatch_pkey" PRIMARY KEY ("id"));
CREATE TABLE "UserVerificationRequest" ("id" TEXT NOT NULL,"userId" TEXT NOT NULL,"type" "VerificationRequestType" NOT NULL,"status" "VerificationRequestStatus" NOT NULL DEFAULT 'PENDING',"documentUrl" TEXT,"reviewedByAdminId" TEXT,"rejectionReason" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "UserVerificationRequest_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ItemVerification" ("id" TEXT NOT NULL,"itemId" TEXT NOT NULL,"type" "ItemVerificationType" NOT NULL,"documentUrl" TEXT,"serialNumberMasked" TEXT,"status" "ItemVerificationStatus" NOT NULL DEFAULT 'PENDING',"reviewedByAdminId" TEXT,"rejectionReason" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "ItemVerification_pkey" PRIMARY KEY ("id"));
CREATE TABLE "VerificationQuestion" ("id" TEXT NOT NULL,"conversationId" TEXT NOT NULL,"itemId" TEXT NOT NULL,"question" TEXT NOT NULL,"status" "VerificationQuestionStatus" NOT NULL DEFAULT 'DRAFT',"answer" TEXT,"askedByOwnerId" TEXT,"answeredAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "VerificationQuestion_pkey" PRIMARY KEY ("id"));
CREATE TABLE "RecoveryRequest" ("id" TEXT NOT NULL,"itemId" TEXT NOT NULL,"ownerId" TEXT NOT NULL,"foundReportId" TEXT,"conversationId" TEXT,"finderIdentityId" TEXT,"source" "RecoverySource" NOT NULL,"status" "RecoveryStatus" NOT NULL DEFAULT 'REGISTERED',"scheduledMeetingLocation" TEXT,"scheduledMeetingTime" TIMESTAMP(3),"ownerConfirmation" BOOLEAN,"finderConfirmation" BOOLEAN,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "RecoveryRequest_pkey" PRIMARY KEY ("id"));
CREATE TABLE "RecoveryTimelineEvent" ("id" TEXT NOT NULL,"recoveryRequestId" TEXT NOT NULL,"type" TEXT NOT NULL,"title" TEXT NOT NULL,"description" TEXT NOT NULL,"actorType" "RecoveryActorType" NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "RecoveryTimelineEvent_pkey" PRIMARY KEY ("id"));

CREATE INDEX "ItemImage_itemId_sortOrder_idx" ON "ItemImage"("itemId","sortOrder");
CREATE UNIQUE INDEX "Category_name_key" ON "Category"("name"); CREATE UNIQUE INDEX "Category_slug_key" ON "Category"("slug"); CREATE INDEX "Category_isActive_idx" ON "Category"("isActive");
CREATE INDEX "FoundReport_status_createdAt_idx" ON "FoundReport"("status","createdAt"); CREATE INDEX "FoundReport_category_foundLocation_idx" ON "FoundReport"("category","foundLocation"); CREATE INDEX "FoundReport_recoveryCode_idx" ON "FoundReport"("recoveryCode");
CREATE INDEX "FoundReportImage_foundReportId_idx" ON "FoundReportImage"("foundReportId"); CREATE INDEX "FoundReportMatch_itemId_status_idx" ON "FoundReportMatch"("itemId","status"); CREATE UNIQUE INDEX "FoundReportMatch_foundReportId_itemId_key" ON "FoundReportMatch"("foundReportId","itemId");
CREATE INDEX "UserVerificationRequest_userId_status_idx" ON "UserVerificationRequest"("userId","status"); CREATE INDEX "ItemVerification_itemId_status_idx" ON "ItemVerification"("itemId","status"); CREATE INDEX "VerificationQuestion_conversationId_status_idx" ON "VerificationQuestion"("conversationId","status");
CREATE INDEX "RecoveryRequest_ownerId_status_idx" ON "RecoveryRequest"("ownerId","status"); CREATE INDEX "RecoveryRequest_itemId_createdAt_idx" ON "RecoveryRequest"("itemId","createdAt"); CREATE INDEX "RecoveryTimelineEvent_recoveryRequestId_createdAt_idx" ON "RecoveryTimelineEvent"("recoveryRequestId","createdAt");
CREATE INDEX "Conversation_foundReportId_idx" ON "Conversation"("foundReportId"); CREATE INDEX "Conversation_finderIdentityId_idx" ON "Conversation"("finderIdentityId"); CREATE UNIQUE INDEX "Item_recoveryCode_key" ON "Item"("recoveryCode"); CREATE INDEX "Item_category_status_publicSearchVisible_idx" ON "Item"("category","status","publicSearchVisible"); CREATE INDEX "Item_brand_color_idx" ON "Item"("brand","color");

ALTER TABLE "ItemImage" ADD CONSTRAINT "ItemImage_itemId_fkey" FOREIGN KEY ("itemId") REFERENCES "Item"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Conversation" ADD CONSTRAINT "Conversation_foundReportId_fkey" FOREIGN KEY ("foundReportId") REFERENCES "FoundReport"("id") ON DELETE SET NULL ON UPDATE CASCADE; ALTER TABLE "Conversation" ADD CONSTRAINT "Conversation_finderIdentityId_fkey" FOREIGN KEY ("finderIdentityId") REFERENCES "FinderIdentity"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "ChatMessage" ADD CONSTRAINT "ChatMessage_finderIdentityId_fkey" FOREIGN KEY ("finderIdentityId") REFERENCES "FinderIdentity"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "FoundReport" ADD CONSTRAINT "FoundReport_finderIdentityId_fkey" FOREIGN KEY ("finderIdentityId") REFERENCES "FinderIdentity"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "FoundReportImage" ADD CONSTRAINT "FoundReportImage_foundReportId_fkey" FOREIGN KEY ("foundReportId") REFERENCES "FoundReport"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "FoundReportMatch" ADD CONSTRAINT "FoundReportMatch_foundReportId_fkey" FOREIGN KEY ("foundReportId") REFERENCES "FoundReport"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "FoundReportMatch" ADD CONSTRAINT "FoundReportMatch_itemId_fkey" FOREIGN KEY ("itemId") REFERENCES "Item"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "UserVerificationRequest" ADD CONSTRAINT "UserVerificationRequest_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "ItemVerification" ADD CONSTRAINT "ItemVerification_itemId_fkey" FOREIGN KEY ("itemId") REFERENCES "Item"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "VerificationQuestion" ADD CONSTRAINT "VerificationQuestion_conversationId_fkey" FOREIGN KEY ("conversationId") REFERENCES "Conversation"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "VerificationQuestion" ADD CONSTRAINT "VerificationQuestion_itemId_fkey" FOREIGN KEY ("itemId") REFERENCES "Item"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "RecoveryRequest" ADD CONSTRAINT "RecoveryRequest_itemId_fkey" FOREIGN KEY ("itemId") REFERENCES "Item"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "RecoveryRequest" ADD CONSTRAINT "RecoveryRequest_ownerId_fkey" FOREIGN KEY ("ownerId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "RecoveryRequest" ADD CONSTRAINT "RecoveryRequest_foundReportId_fkey" FOREIGN KEY ("foundReportId") REFERENCES "FoundReport"("id") ON DELETE SET NULL ON UPDATE CASCADE; ALTER TABLE "RecoveryRequest" ADD CONSTRAINT "RecoveryRequest_conversationId_fkey" FOREIGN KEY ("conversationId") REFERENCES "Conversation"("id") ON DELETE SET NULL ON UPDATE CASCADE; ALTER TABLE "RecoveryRequest" ADD CONSTRAINT "RecoveryRequest_finderIdentityId_fkey" FOREIGN KEY ("finderIdentityId") REFERENCES "FinderIdentity"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "RecoveryTimelineEvent" ADD CONSTRAINT "RecoveryTimelineEvent_recoveryRequestId_fkey" FOREIGN KEY ("recoveryRequestId") REFERENCES "RecoveryRequest"("id") ON DELETE CASCADE ON UPDATE CASCADE;

UPDATE "Item" SET "recoveryCode" = 'KP-' || UPPER(SUBSTRING(MD5("id") FROM 1 FOR 6)) WHERE "recoveryCode" IS NULL;
