import assert from "node:assert/strict";import test from "node:test";import { assertClaimTransition,nextClaimAction } from "../../lib/claims/state-machine";import { decryptClaimSecret,encryptClaimSecret,hashClaimAnswer } from "../../lib/claims/encryption";import { questionsForCategory } from "../../lib/claims/templates";
const actor={actorId:"requester",role:"USER" as const,requesterId:"requester",recipientId:"owner",blocked:false};
test("claim state machine accepts valid participant transitions",()=>assert.doesNotThrow(()=>assertClaimTransition({...actor,current:"DRAFT",next:"SUBMITTED"})));
test("claim state machine rejects invalid and unrelated transitions",()=>{assert.throws(()=>assertClaimTransition({...actor,current:"DRAFT",next:"RECOVERY_CONFIRMED"}));assert.throws(()=>assertClaimTransition({...actor,actorId:"other",current:"DRAFT",next:"SUBMITTED"}))});
test("verification approval requires completed answers and owner/admin",()=>{assert.throws(()=>assertClaimTransition({...actor,current:"UNDER_REVIEW",next:"VERIFIED",requiredAnswersComplete:true}));assert.doesNotThrow(()=>assertClaimTransition({...actor,actorId:"owner",current:"UNDER_REVIEW",next:"VERIFIED",requiredAnswersComplete:true}))});
test("two confirmations and no dispute are required for recovery",()=>{assert.throws(()=>assertClaimTransition({...actor,current:"RETURNED",next:"RECOVERY_CONFIRMED",bothConfirmed:false}));assert.throws(()=>assertClaimTransition({...actor,current:"RETURNED",next:"RECOVERY_CONFIRMED",bothConfirmed:true,hasOpenDispute:true}));assert.doesNotThrow(()=>assertClaimTransition({...actor,current:"RETURNED",next:"RECOVERY_CONFIRMED",bothConfirmed:true}))});
test("claim secrets use authenticated encryption and normalized hashes",()=>{const previous=process.env.CLAIM_ENCRYPTION_KEY;process.env.CLAIM_ENCRYPTION_KEY=Buffer.alloc(32,7).toString("base64");const cipher=encryptClaimSecret("private answer");assert.notEqual(cipher,"private answer");assert.equal(decryptClaimSecret(cipher),"private answer");assert.equal(hashClaimAnswer("  Blue  Case "),hashClaimAnswer("blue case"));process.env.CLAIM_ENCRYPTION_KEY=previous});
test("category templates avoid unsafe credentials",()=>{const text=questionsForCategory("MOBILE","Lost blue phone").map(q=>q.text).join(" ").toLowerCase();for(const forbidden of ["full imei","pin?","password?"])assert.equal(text.includes(forbidden),false)});
test("next action is participant-aware",()=>{assert.equal(nextClaimAction("SUBMITTED",true),"Wait for review");assert.equal(nextClaimAction("SUBMITTED",false),"Review claim")});
