"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import {
  Activity, ArrowUpRight, BarChart3, CheckCircle2, CircleDollarSign, Clock3,
  Download, FileSearch, Flag, HeartHandshake, HelpCircle, LayoutDashboard,
  MapPin, PackageCheck, PackageSearch, QrCode, RefreshCw,
  ScanLine, ShieldCheck, Sparkles, Trophy, UserCheck, Users, WalletCards,
} from "lucide-react";

type Data = {
  metrics: Record<string, number>;
  moderation: { approved:number;underReview:number;rejected:number;total:number };
  trends: { labels:string[];users:number[];posts:number[];recoveries:number[];scans:number[];revenue:number[] };
  heatmap:number[][];
  rankings:{categories:Rank[];cities:Rank[];countries:Rank[];activeUsers:UserRank[];helpfulUsers:UserRank[]};
  activity:Array<{id:string;type:string;title:string;detail?:string;at:string}>;
  updatedAt:string;
};
type Rank={label:string;value:number};type UserRank={id:string;name:string;email:string;value:number;detail:string;trustScore:number};

const metricCards = [
  ["todayUsers","Today’s Users",Users,"users"],["dailyActiveUsers","Daily Active Users",Activity,"users"],["monthlyActiveUsers","Monthly Active Users",Users,"users"],
  ["lostReports","Lost Reports",PackageSearch,"reports"],["foundReports","Found Reports",PackageCheck,"reports"],["needHelpPosts","Need Help Posts",HelpCircle,"posts"],
  ["recoveredItems","Recovered Items",CheckCircle2,"items"],["recoverySuccessRate","Recovery Success Rate",HeartHandshake,"percent"],["averageRecoveryHours","Average Recovery Time",Clock3,"hours"],
  ["communityPosts","Community Posts",Sparkles,"posts"],["pendingClaims","Pending Claims",FileSearch,"claims"],["openRecoveryRequests","Open Recovery Requests",Flag,"requests"],
  ["verifiedUsers","Verified Users",UserCheck,"users"],["communityHeroes","Community Heroes",Trophy,"heroes"],["spamBlocked","Spam Blocked",ShieldCheck,"cases"],
  ["reportsPendingReview","Pending Review",Flag,"reports"],["revenue","Revenue",CircleDollarSign,"currency"],["subscriptions","Subscriptions",WalletCards,"active"],
  ["premiumUsers","Premium Users",Sparkles,"users"],["qrRegistrations","QR Registrations",QrCode,"codes"],["qrScans","QR Scans",ScanLine,"scans"],
] as const;

const quickActions=[["Moderation queue","/admin/moderation",ShieldCheck],["Review claims","/admin/disputes",FileSearch],["Recovery requests","/admin/recovery-requests",HeartHandshake],["Verification requests","/admin/verification-requests",UserCheck],["Payments","/admin/payments",CircleDollarSign],["Bulk activity","/admin/bulk-activity",BarChart3]] as const;

export default function AdminAnalyticsCenter(){
  const[data,setData]=useState<Data|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState("");
  async function load(){setLoading(true);setError("");try{const response=await fetch("/api/admin/analytics",{cache:"no-store"});const body=await response.json();if(!response.ok)throw new Error(body.message||"Unable to load analytics");setData(body.data)}catch(cause){setError(cause instanceof Error?cause.message:"Unable to load analytics")}finally{setLoading(false)}}
  useEffect(()=>{let active=true;async function refresh(){try{const response=await fetch("/api/admin/analytics",{cache:"no-store"}),body=await response.json();if(active&&response.ok)setData(body.data)}catch{}finally{if(active)setLoading(false)}}void refresh();const timer=window.setInterval(()=>void refresh(),60_000);return()=>{active=false;window.clearInterval(timer)}},[]);
  function exportReport(){if(!data)return;const rows=[["Metric","Value"],...metricCards.map(([key,label])=>[label,String(data.metrics[key]??0)]),[],["Moderation","Value"],["Approved",String(data.moderation.approved)],["Under review",String(data.moderation.underReview)],["Rejected",String(data.moderation.rejected)]];const csv=rows.map(row=>row.map(cell=>`"${cell.replaceAll('"','""')}"`).join(",")).join("\n"),url=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"})),anchor=document.createElement("a");anchor.href=url;anchor.download=`khoya-paya-admin-report-${new Date().toISOString().slice(0,10)}.csv`;anchor.click();URL.revokeObjectURL(url)}
  return <div className="admin-center">
    <aside className="admin-rail"><Link className="admin-rail-brand" href="/"><span>K</span><strong>Khoya Paya</strong></Link><nav><Link className="active" href="/admin"><LayoutDashboard size={18}/>Overview</Link>{quickActions.map(([label,href,Icon])=><Link href={href} key={href}><Icon size={18}/>{label}</Link>)}</nav><div className="admin-rail-trust"><ShieldCheck size={22}/><strong>Admin protected</strong><small>Role-based access active</small></div></aside>
    <main className="admin-workspace"><header className="admin-top"><div><span>Operations intelligence</span><h1>Analytics center</h1><p>Real-time trust, recovery, community and revenue health.</p></div><div className="admin-top-actions"><span className="admin-live"><i/>Live · {data?relative(data.updatedAt):"connecting"}</span><button type="button" onClick={()=>void load()} disabled={loading}><RefreshCw className={loading?"spin":""} size={17}/>Refresh</button><button type="button" onClick={exportReport} disabled={!data}><Download size={17}/>Export report</button></div></header>
    {error&&!data?<div className="admin-error"><ShieldCheck size={30}/><strong>Analytics could not be loaded.</strong><p>{error}</p><button onClick={()=>void load()}>Try again</button></div>:loading&&!data?<AdminSkeleton/>:data&&<>
      <section className="admin-metric-grid">{metricCards.map(([key,label,Icon,format],index)=><Metric key={key} label={label} value={data.metrics[key]??0} format={format} icon={Icon} featured={["recoveredItems","recoverySuccessRate","revenue"].includes(key)} index={index}/>)}</section>
      <section className="admin-chart-grid"><article className="admin-panel admin-trend-panel"><PanelTitle eyebrow="30-day trend" title="Platform growth & recovery signals" icon={Activity}/><TrendChart labels={data.trends.labels} series={[{name:"Users",values:data.trends.users,color:"#0052f2"},{name:"Posts",values:data.trends.posts,color:"#16734a"},{name:"Recoveries",values:data.trends.recoveries,color:"#d39223"},{name:"QR scans",values:data.trends.scans,color:"#4f77bd"}]}/></article><article className="admin-panel moderation-panel"><PanelTitle eyebrow="AI moderation" title="Content safety decisions" icon={ShieldCheck}/><ModerationDonut data={data.moderation}/></article></section>
      <section className="admin-chart-grid"><article className="admin-panel"><PanelTitle eyebrow="QR behavior" title="Scan activity heatmap" icon={ScanLine}/><Heatmap values={data.heatmap}/></article><article className="admin-panel"><PanelTitle eyebrow="Revenue trend" title="Paid revenue · last 30 days" icon={CircleDollarSign}/><TrendChart labels={data.trends.labels} compact series={[{name:"Revenue",values:data.trends.revenue,color:"#0052f2"}]}/></article></section>
      <section className="admin-ranking-grid"><Ranking title="Top categories" icon={BarChart3} rows={data.rankings.categories}/><Ranking title="Top cities" icon={MapPin} rows={data.rankings.cities}/><Ranking title="Top countries" icon={MapPin} rows={data.rankings.countries}/></section>
      <section className="admin-people-grid"><UserRanking title="Most active users" rows={data.rankings.activeUsers}/><UserRanking title="Most helpful users" rows={data.rankings.helpfulUsers}/></section>
      <section className="admin-bottom-grid"><article className="admin-panel recent-admin-activity"><PanelTitle eyebrow="Live operations" title="Recent activity" icon={Activity}/>{data.activity.length?<div>{data.activity.map(item=><article key={item.id}><span className={`activity-icon ${item.type.toLowerCase()}`}>{activityIcon(item.type)}</span><div><strong>{item.title}</strong><small>{item.detail||item.type.toLowerCase()}</small></div><time>{relative(item.at)}</time></article>)}</div>:<p>No recent activity.</p>}</article><article className="admin-panel quick-admin-actions"><PanelTitle eyebrow="Workspaces" title="Quick actions" icon={ArrowUpRight}/><div>{quickActions.map(([label,href,Icon])=><Link href={href} key={href}><span><Icon size={18}/></span><strong>{label}</strong><ArrowUpRight size={16}/></Link>)}</div></article></section>
    </>}</main>
  </div>}

function Metric({label,value,format,icon:Icon,featured,index}:{label:string;value:number;format:string;icon:typeof Users;featured:boolean;index:number}){return <article className={`admin-metric ${featured?"featured":""}`} style={{animationDelay:`${index*20}ms`}}><span><Icon size={19}/></span><strong>{formatValue(value,format)}</strong><small>{label}</small></article>}
function formatValue(value:number,format:string){if(format==="percent")return `${value.toFixed(1)}%`;if(format==="hours")return value<24?`${value.toFixed(1)}h`:`${(value/24).toFixed(1)}d`;if(format==="currency")return `₹${value.toLocaleString("en-IN",{maximumFractionDigits:0})}`;return value.toLocaleString("en-IN")}
function PanelTitle({eyebrow,title,icon:Icon}:{eyebrow:string;title:string;icon:typeof Activity}){return <header className="admin-panel-title"><div><span>{eyebrow}</span><h2>{title}</h2></div><Icon size={22}/></header>}
function TrendChart({labels,series,compact=false}:{labels:string[];series:Array<{name:string;values:number[];color:string}>;compact?:boolean}){const width=720,height=compact?190:260,pad=24,max=Math.max(1,...series.flatMap(item=>item.values));const points=(values:number[])=>values.map((value,index)=>`${pad+(index/Math.max(1,values.length-1))*(width-pad*2)},${height-pad-(value/max)*(height-pad*2)}`).join(" ");return <div className="trend-chart"><div className="chart-legend">{series.map(item=><span key={item.name}><i style={{background:item.color}}/>{item.name}</span>)}</div><svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label="Analytics trend graph"><defs>{series.map(item=><linearGradient id={`fill-${item.name.replaceAll(" ","")}`} x1="0" x2="0" y1="0" y2="1" key={item.name}><stop offset="0" stopColor={item.color} stopOpacity=".2"/><stop offset="1" stopColor={item.color} stopOpacity="0"/></linearGradient>)}</defs>{[.25,.5,.75,1].map(step=><line key={step} x1={pad} x2={width-pad} y1={height-pad-(height-pad*2)*step} y2={height-pad-(height-pad*2)*step} stroke="#e7e2ed" strokeDasharray="4 6"/>)}{series.map(item=><g key={item.name}><polyline points={points(item.values)} fill="none" stroke={item.color} strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"/></g>)}</svg><div className="chart-axis"><span>{labels[0]}</span><span>{labels[Math.floor(labels.length/2)]}</span><span>{labels.at(-1)}</span></div></div>}
function ModerationDonut({data}:{data:Data["moderation"]}){const total=Math.max(1,data.total),approved=data.approved/total*100,review=data.underReview/total*100;return <div className="moderation-donut-wrap"><div className="moderation-donut" style={{background:`conic-gradient(#16734a 0 ${approved}%,#d39223 ${approved}% ${approved+review}%,#c2412d ${approved+review}% 100%)`}}><span><strong>{data.total.toLocaleString("en-IN")}</strong><small>decisions</small></span></div><div className="moderation-breakdown"><p><i className="approved"/>Approved <strong>{data.approved}</strong></p><p><i className="review"/>Under review <strong>{data.underReview}</strong></p><p><i className="rejected"/>Rejected <strong>{data.rejected}</strong></p></div></div>}
function Heatmap({values}:{values:number[][]}){const max=Math.max(1,...values.flat()),days=["Sun","Mon","Tue","Wed","Thu","Fri","Sat"];return <div className="admin-heatmap"><div className="heat-hours"><span>12am</span><span>6am</span><span>12pm</span><span>6pm</span></div>{values.map((row,index)=><div className="heat-row" key={days[index]}><strong>{days[index]}</strong>{row.map((value,hour)=><i key={hour} title={`${days[index]} ${hour}:00 · ${value} scans`} style={{opacity:.12+(value/max)*.88}}/>)}</div>)}<small>Lower activity <i/><i/><i/><i/> Higher activity</small></div>}
function Ranking({title,icon:Icon,rows}:{title:string;icon:typeof MapPin;rows:Rank[]}){const max=Math.max(1,...rows.map(row=>row.value));return <article className="admin-panel rank-panel"><PanelTitle eyebrow="Distribution" title={title} icon={Icon}/>{rows.length?<ol>{rows.map((row,index)=><li key={row.label}><span>{index+1}</span><div><strong>{row.label}</strong><i><b style={{width:`${row.value/max*100}%`}}/></i></div><em>{row.value}</em></li>)}</ol>:<div className="admin-inline-empty"><Icon size={20}/><strong>No activity in this period</strong><small>This panel will populate from verified platform events.</small></div>}</article>}
function UserRanking({title,rows}:{title:string;rows:UserRank[]}){return <article className="admin-panel user-rank-panel"><PanelTitle eyebrow="Community intelligence" title={title} icon={Users}/>{rows.length?<div>{rows.map((user,index)=><article key={user.id}><span>{index+1}</span><strong className="admin-avatar">{user.name.slice(0,1).toUpperCase()}</strong><div><b>{user.name}</b><small>{user.detail}</small></div><em>{user.value} pts</em></article>)}</div>:<p>No ranked users yet.</p>}</article>}
function activityIcon(type:string){if(type==="USER")return <Users size={16}/>;if(type==="RECOVERY")return <CheckCircle2 size={16}/>;if(type==="PAYMENT")return <CircleDollarSign size={16}/>;return <Sparkles size={16}/>}
function relative(value:string){const seconds=Math.max(1,Math.floor((Date.now()-new Date(value).getTime())/1000));if(seconds<60)return"just now";const minutes=Math.floor(seconds/60);if(minutes<60)return`${minutes}m ago`;const hours=Math.floor(minutes/60);if(hours<24)return`${hours}h ago`;return`${Math.floor(hours/24)}d ago`}
function AdminSkeleton(){return <div className="admin-skeleton">{Array.from({length:12},(_,index)=><i key={index}/>)}</div>}
