"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";

type Case = { id:string; createdAt:string; targetType:string; targetId:string; decision:string; riskScore:number; reasonCode:string; provider:string; ownerName:string|null; signals:string[]; lastAction:string|null };
export default function ModerationQueue({cases}:{cases:Case[]}) {
  const router=useRouter();const[selected,setSelected]=useState<string[]>([]);const[pending,setPending]=useState<{ids:string[];action:string}|null>(null);const[reason,setReason]=useState("");const[busy,setBusy]=useState(false);const[notice,setNotice]=useState("");
  async function apply(){if(!pending||reason.trim().length<3)return;setBusy(true);const results=await Promise.allSettled(pending.ids.slice(0,25).map(async id=>{const response=await fetch(`/api/admin/moderation/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:pending.action,reason})});if(!response.ok)throw new Error((await response.json()).message||"Action failed") }));const failed=results.filter(result=>result.status==="rejected").length;setNotice(failed?`${results.length-failed} updated; ${failed} failed.`:`${results.length} case(s) updated.`);setBusy(false);setPending(null);setReason("");setSelected([]);router.refresh()}
  return <><div className="table-responsive"><table className="table align-middle"><thead><tr><th><span className="visually-hidden">Select</span></th><th>Created</th><th>Target</th><th>Risk</th><th>Decision</th><th>Provider / signals</th><th>Latest action</th><th>Actions</th></tr></thead><tbody>{cases.map(item=><tr key={item.id}><td><input type="checkbox" checked={selected.includes(item.id)} onChange={e=>setSelected(current=>e.target.checked?[...current,item.id]:current.filter(id=>id!==item.id))}/></td><td>{new Date(item.createdAt).toLocaleString()}</td><td><strong>{item.targetType}</strong><br/><small>{item.ownerName||"Unknown user"}</small></td><td>{Math.round(item.riskScore*100)}%<br/><small>{item.reasonCode}</small></td><td>{item.decision}</td><td>{item.provider}<br/><small>{item.signals.join(", ")||"None"}</small></td><td>{item.lastAction||"Pending"}</td><td><Link href={`/admin/moderation/${item.id}`}>Open</Link> <button type="button" onClick={()=>setPending({ids:[item.id],action:"APPROVE"})}>Approve</button> <button type="button" onClick={()=>setPending({ids:[item.id],action:"REJECT"})}>Reject</button></td></tr>)}</tbody></table></div>{selected.length>0&&<div className="d-flex gap-2 align-items-center"><strong>{selected.length} selected</strong>{["APPROVE","REJECT","HIDE"].map(action=><button key={action} type="button" onClick={()=>setPending({ids:selected,action})}>{action.toLowerCase()}</button>)}</div>}{notice&&<p role="status">{notice}</p>}{pending&&<div className="composer-modal-backdrop"><div className="composer-modal" role="dialog" aria-modal="true"><header><h2>Confirm {pending.action.toLowerCase()}</h2></header><p>This action affects {pending.ids.length} moderation case(s). Every target receives an audit entry.</p><label>Reason<textarea value={reason} maxLength={1000} onChange={e=>setReason(e.target.value)}/></label><footer><button type="button" disabled={busy} onClick={()=>setPending(null)}>Cancel</button><button type="button" disabled={busy||reason.trim().length<3} onClick={apply}>{busy?"Applying…":"Confirm"}</button></footer></div></div>}</>;
}
