"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import {
  Award, Bell, Bot, CheckCircle2, ChevronRight, Globe2, HandHeart, Heart,
  Languages, LockKeyhole, MessageCircle, PackageCheck, PackageSearch,
  QrCode, Quote, ScanLine, ShieldCheck, Smartphone, Sparkles, Star,
  UserCheck, WalletCards,
} from "lucide-react";

type Testimonial={id:string;title:string;quote:string;author:string;verificationLevel:string;trustScore:number;location:string};

const journeys=[
  {title:"I Lost Something",copy:"Create a privacy-safe report, reach nearby helpers and manage every recovery step in one place.",cta:"Start my lost report",href:"/signup",tone:"lost",Icon:PackageSearch},
  {title:"I Found Something",copy:"Help an item find its owner without sharing your personal details or handling the recovery alone.",cta:"Report what I found",href:"/report-found-item",tone:"found",Icon:PackageCheck},
  {title:"I Want to Help",copy:"Discover genuine requests, share useful leads and build a trusted record of community impact.",cta:"Join as a helper",href:"/signup",tone:"help",Icon:HandHeart},
  {title:"Protect My Items with QR",copy:"Give valuables a private recovery link so an honest finder always has a safe way to reach you.",cta:"Protect my first item",href:"/signup",tone:"qr",Icon:QrCode},
];
const features=[
  [PackageSearch,"Lost Reports","Create clear, privacy-safe alerts that people can act on."],[PackageCheck,"Found Reports","Return something without exposing personal contact details."],[QrCode,"QR Recovery","Turn one scan into a direct, protected path home."],[HandHeart,"Community Help","Ask for support and contribute useful local knowledge."],
  [MessageCircle,"Secure Chat","Coordinate recovery inside the platform, not in public comments."],[UserCheck,"Smart Verification","Confirm ownership with private, item-specific questions."],[Bot,"AI Moderation","Detect risky, irrelevant and suspicious content before it spreads."],[ShieldCheck,"Trust Score","Understand community contribution through transparent signals."],
  [WalletCards,"Rewards","Recognise helpful outcomes while keeping recovery safe."],[Award,"Badges","Celebrate verified returns, trust and consistent contribution."],[Bell,"Notifications","Stay informed when someone scans, messages or finds a match."],[Languages,"Multi-language","Designed to make community recovery easier across languages."],
] as const;

export function ChooseJourney(){return <section className="guest-journeys" id="community-help"><div className="community-container"><header className="guest-section-heading"><span>Choose your journey</span><h2>One platform. Four ways to make a difference.</h2><p>Whether you need help or want to offer it, your next step should feel obvious and safe.</p></header><div className="journey-grid">{journeys.map(({title,copy,cta,href,tone,Icon})=><article className={`journey-card ${tone}`} key={title}><div className="journey-visual"><span className="journey-orbit"/><Icon size={42}/><i><ShieldCheck size={16}/></i></div><span className="journey-number">0{journeys.findIndex(item=>item.title===title)+1}</span><h3>{title}</h3><p>{copy}</p><Link href={href}>{cta}<ChevronRight size={17}/></Link></article>)}</div></div></section>}

export function PlatformFeatures(){return <section className="guest-features" id="features"><div className="community-container"><header className="guest-section-heading centered"><span>Built for the entire recovery journey</span><h2>Powerful technology.<br/>Reassuringly human.</h2><p>Every feature exists to make asking for help safer, helping others easier and successful returns more likely.</p></header><div className="guest-feature-grid">{features.map(([Icon,title,copy],index)=><article key={title}><span><Icon size={23}/></span><small>{String(index+1).padStart(2,"0")}</small><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section>}

export function VerifiedTestimonials(){const[items,setItems]=useState<Testimonial[]>([]),[loaded,setLoaded]=useState(false);useEffect(()=>{let active=true;fetch("/api/community/impact",{cache:"no-store"}).then(response=>response.ok?response.json():null).then(body=>{if(active){setItems(body?.data?.testimonials??[]);setLoaded(true)}}).catch(()=>active&&setLoaded(true));return()=>{active=false}},[]);return <section className="verified-testimonials"><div className="community-container"><header className="guest-section-heading"><span>Verified recovery stories</span><h2>Trust grows when real people share real outcomes.</h2><p>Only public success stories from verified members appear here.</p></header>{items.length?<div className="testimonial-grid">{items.slice(0,3).map(item=><article key={item.id}><Quote size={25}/><div className="testimonial-stars"><Star size={13}/><Star size={13}/><Star size={13}/><Star size={13}/><Star size={13}/></div><h3>{item.title}</h3><p>“{item.quote}”</p><footer><span>{item.author.slice(0,1).toUpperCase()}</span><div><strong>{item.author}</strong><small><CheckCircle2 size={12}/>{item.verificationLevel.replaceAll("_"," ")} verified{item.location?` · ${item.location}`:""}</small></div></footer></article>)}</div>:<div className="testimonial-empty"><ShieldCheck size={30}/><strong>{loaded?"Verified stories are being collected.":"Loading verified stories…"}</strong><p>Success stories appear only after consent and verification—never as invented social proof.</p></div>}</div></section>}

export function AppDownload(){return <section className="guest-app"><div className="community-container guest-app-panel"><div><span className="guest-app-kicker"><Smartphone size={16}/>Mobile experience</span><h2>Community recovery,<br/>wherever life happens.</h2><p>Save protected items, follow recovery progress and respond to important alerts from one mobile-first experience.</p><div className="app-store-row"><button type="button" disabled><Globe2 size={20}/><span><small>Android app</small><strong>Coming soon</strong></span></button><button type="button" disabled><Smartphone size={20}/><span><small>iPhone app</small><strong>Coming soon</strong></span></button></div><small className="app-honesty"><LockKeyhole size={14}/>The responsive web app is available today. Native apps are not yet released.</small></div><div className="app-phone-art"><div className="app-phone-speaker"/><span className="app-phone-brand"><Heart size={16}/>Khoya Paya</span><div className="app-recovery-alert"><i><CheckCircle2 size={18}/></i><span><strong>Possible match found</strong><small>Open the secure recovery chat</small></span></div><div className="app-qr-tile"><QrCode size={86}/><strong>Your protected QR</strong><small>Ready to scan</small></div><div className="app-mini-nav"><PackageSearch size={18}/><ScanLine size={18}/><Bell size={18}/></div></div></div></section>}

export function GuestFinalCTA(){return <section className="guest-final-cta"><div className="community-container"><span><Sparkles size={17}/>A safer, kinder recovery network starts with you</span><h2>Recover What Matters.<br/><em>Help Someone Today.</em></h2><p>Join a trusted global community where people recover lost items, help others and build trust together.</p><div><Link className="guest-final-lost" href="/signup"><PackageSearch size={18}/>Report Lost Item</Link><Link className="guest-final-found" href="/report-found-item"><PackageCheck size={18}/>Report Found Item</Link><Link className="guest-final-account" href="/signup">Create Free Account <ChevronRight size={17}/></Link></div><small><ShieldCheck size={14}/>Free to join · Privacy-first · Built for genuine recovery</small></div></section>}
