ALTER TYPE "CommunityReportReason" ADD VALUE IF NOT EXISTS 'WRONG_CATEGORY';
ALTER TYPE "CommunityReportReason" ADD VALUE IF NOT EXISTS 'ADULT_CONTENT';
ALTER TYPE "CommunityReportReason" ADD VALUE IF NOT EXISTS 'VIOLENCE';
ALTER TYPE "CommunityReportReason" ADD VALUE IF NOT EXISTS 'COPYRIGHT';
