import { z } from "zod";import { CommunityContactPreference,CommunityItemCategory,CommunityPostStatus,CommunityPostType,CommunityVisibility,PostMediaType } from "@prisma/client";import { communityLimits } from "@/lib/community/config";
const optionalText=(max:number)=>z.string().trim().max(max).optional().nullable();const coordinate=z.coerce.number().min(-180).max(180).optional().nullable();const privatePattern=/(?:\b[\w.%+-]+@[\w.-]+\.[A-Za-z]{2,}\b|(?:\+?\d[\d\s-]{8,}\d))/;
const publicText=z.string().trim().refine(value=>!privatePattern.test(value),"Do not include phone numbers or email addresses in public fields.");
export const tagSchema=z.string().trim().min(1).max(communityLimits.maxTagLength).regex(/^[\p{L}\p{N}][\p{L}\p{N}\s-]*$/u,"Tags may contain letters, numbers, spaces, and hyphens.");
const communityPostBaseSchema=z.object({postType:z.nativeEnum(CommunityPostType).default("NEED_HELP"),itemCategory:z.nativeEnum(CommunityItemCategory).default("OTHER"),title:publicText.max(communityLimits.maxTitleLength).default(""),description:publicText.max(communityLimits.maxDescriptionLength).default(""),visibility:z.nativeEnum(CommunityVisibility).default("PUBLIC"),rewardOffered:z.boolean().default(false),rewardAmount:z.coerce.number().min(0).max(10000000).optional().nullable(),rewardCurrency:z.string().trim().length(3).toUpperCase().default("INR"),eventDate:z.coerce.date().optional().nullable(),publicLocationName:optionalText(160),city:optionalText(100),state:optionalText(100),country:optionalText(100),postalCode:optionalText(20),publicLatitude:coordinate,publicLongitude:coordinate,privateLatitude:coordinate,privateLongitude:coordinate,contactPreference:z.nativeEnum(CommunityContactPreference).default("PLATFORM_MESSAGE"),allowComments:z.boolean().default(true),allowSharing:z.boolean().default(true),tags:z.array(tagSchema).max(communityLimits.maxTags).default([]),mediaIds:z.array(z.string().cuid()).max(communityLimits.maxImages+communityLimits.maxVideos).default([]),intent:z.enum(["DRAFT","PUBLISH"]).default("DRAFT")});
function publishingRules(data:z.infer<typeof communityPostBaseSchema>,ctx:z.RefinementCtx){if(data.intent==="PUBLISH"){if(data.title.length<5)ctx.addIssue({code:"custom",path:["title"],message:"Published posts need a title of at least 5 characters."});if(data.description.length<20)ctx.addIssue({code:"custom",path:["description"],message:"Published posts need a description of at least 20 characters."});if(!data.eventDate&&!(["NEED_HELP","COMMUNITY_UPDATE","SUCCESS_STORY"] as string[]).includes(data.postType))ctx.addIssue({code:"custom",path:["eventDate"],message:"Event date is required to publish this post."});if(!data.publicLocationName&&!data.city&&!(["COMMUNITY_UPDATE","SUCCESS_STORY"] as string[]).includes(data.postType))ctx.addIssue({code:"custom",path:["publicLocationName"],message:"A public area or city is required to publish this post."})}if(data.visibility==="FOLLOWERS_ONLY")ctx.addIssue({code:"custom",path:["visibility"],message:"Followers-only posts are unavailable until following is enabled."});if(data.rewardOffered&&data.rewardAmount==null)ctx.addIssue({code:"custom",path:["rewardAmount"],message:"Enter a reward amount or turn off reward."})}
export const communityPostInputSchema=communityPostBaseSchema.superRefine(publishingRules);
export const communityPostUpdateSchema=communityPostBaseSchema.omit({intent:true}).partial();
export const feedQuerySchema=z.object({cursor:z.string().cuid().optional(),limit:z.coerce.number().int().min(1).max(communityLimits.maxPageSize).default(communityLimits.defaultPageSize),type:z.nativeEnum(CommunityPostType).optional(),category:z.nativeEnum(CommunityItemCategory).optional(),status:z.enum(["PUBLISHED","RECOVERED","CLOSED"]).optional(),city:z.string().trim().max(100).optional(),state:z.string().trim().max(100).optional(),country:z.string().trim().max(100).optional(),rewardOnly:z.coerce.boolean().optional(),mediaType:z.nativeEnum(PostMediaType).optional(),verifiedOnly:z.coerce.boolean().optional(),from:z.coerce.date().optional(),to:z.coerce.date().optional(),search:z.string().trim().max(100).optional(),sort:z.enum(["LATEST","OLDEST","UPDATED","RECOVERED","REWARD"]).default("LATEST")});
export const mediaOrderSchema=z.object({mediaIds:z.array(z.string().cuid()).min(1).max(communityLimits.maxImages+communityLimits.maxVideos)});
export const postStatusActionSchema=z.object({status:z.nativeEnum(CommunityPostStatus).optional()});
