import { notFound } from "next/navigation";
import Link from "next/link";
import { getAdmin } from "@/lib/admin";
import { prisma } from "@/lib/prisma";

export default async function ModerationDetail({params}:{params:Promise<{caseId:string}>}) {
  if(!await getAdmin())notFound();
  const id=(await params).caseId;
  const item=await prisma.moderationCase.findUnique({where:{id},include:{actions:{orderBy:{createdAt:"desc"}}}});
  if(!item)notFound();
  const [post,comment,media,owner,reports]=await Promise.all([
    item.targetType==="POST"?prisma.communityPost.findUnique({where:{id:item.targetId},select:{title:true,description:true,publicLocationName:true,city:true,state:true,country:true,itemCategory:true,postType:true,author:{select:{id:true,name:true,trustScore:true}},media:{where:{deletedAt:null},select:{id:true,url:true,thumbnailUrl:true,mediaType:true,moderationStatus:true}}}}):null,
    item.targetType==="COMMENT"?prisma.communityComment.findUnique({where:{id:item.targetId},select:{content:true,status:true,author:{select:{id:true,name:true,trustScore:true}},post:{select:{id:true,title:true}},parent:{select:{content:true}}}}):null,
    item.targetType==="MEDIA"?prisma.postMedia.findUnique({where:{id:item.targetId},select:{url:true,thumbnailUrl:true,width:true,height:true,duration:true,mimeType:true,fileSize:true,contentHash:true,storageKey:true,createdAt:true,altText:true,processingStatus:true,moderationStatus:true,post:{select:{id:true,title:true,author:{select:{id:true,name:true,trustScore:true}}}}}}):null,
    item.ownerId?prisma.user.findUnique({where:{id:item.ownerId},select:{id:true,name:true,trustScore:true,isBlocked:true}}):null,
    prisma.communityReport.count({where:item.targetType==="POST"?{targetPostId:item.targetId}:item.targetType==="COMMENT"?{targetCommentId:item.targetId}:{}}),
  ]);
  return <main className="container py-5"><Link href="/admin/moderation">← Moderation queue</Link><h1>Moderation case</h1><div className="row g-4"><section className="col-lg-8"><article className="dashboard-message-card"><h2>{post?.title??(comment?"Comment review":media?.altText??item.targetType)}</h2>{post&&<><p>{post.description}</p><dl><dt>Type / category</dt><dd>{post.postType} · {post.itemCategory}</dd><dt>Public location</dt><dd>{[post.publicLocationName,post.city,post.state,post.country].filter(Boolean).join(", ")||"Not provided"}</dd><dt>Reports</dt><dd>{reports}</dd></dl>{post.media.map(asset=><div key={asset.id} role="img" aria-label="Related moderated media" style={{backgroundImage:`url(${asset.thumbnailUrl??asset.url})`,backgroundSize:"contain",backgroundRepeat:"no-repeat",minHeight:320}}/>)}</>}{comment&&<><p>{comment.content}</p><p>Parent post: {comment.post.title}</p>{comment.parent&&<blockquote>{comment.parent.content}</blockquote>}<p>Reports: {reports}</p></>}{media&&<><div>{media.mimeType.startsWith("video/")?<video controls poster={media.thumbnailUrl??undefined} src={media.url} style={{maxWidth:"100%"}}/>:<div role="img" aria-label={media.altText} style={{backgroundImage:`url(${media.url})`,backgroundSize:"contain",backgroundRepeat:"no-repeat",minHeight:480}}/>}</div><dl><dt>Dimensions / duration</dt><dd>{media.width??"?"} × {media.height??"?"} · {media.duration??0}s</dd><dt>MIME / size</dt><dd>{media.mimeType} · {media.fileSize} bytes</dd><dt>SHA-256</dt><dd>{media.contentHash??"Unavailable"}</dd><dt>Storage</dt><dd>{media.storageKey?"Stored securely":"Local/legacy"}</dd><dt>Processing / moderation</dt><dd>{media.processingStatus} · {media.moderationStatus}</dd></dl></>}</article></section><aside className="col-lg-4"><article className="dashboard-message-card"><h2>Decision context</h2><p>{item.decision} · risk {Math.round(item.riskScore*100)}%</p><p>{item.provider} · {item.reasonCode}</p><p>{Array.isArray(item.signals)?item.signals.join(", "):"No signals"}</p><h3>User</h3><p>{post?.author.name??comment?.author.name??media?.post?.author.name??owner?.name??"Unknown"}</p><h3>Audit history</h3>{item.actions.length?item.actions.map(action=><p key={action.id}>{action.action} · {action.reason}<br/><small>{action.createdAt.toLocaleString()}</small></p>):<p>No admin action yet.</p>}</article></aside></div></main>;
}
